<?php include "header.php"; ?>
<?php include "block-banner.php"; ?>
<?php include "block-sp-new.php"; ?>
<?php include "block-clock.php"; ?>
<?php include "block-02.php"; ?>
<?php include "block-donggia.php"; ?>
<?php include "block-sp.php"; ?>
<?php include "block-01.php"; ?>
<?php include "block-dky.php"; ?>
<?php include "block-kh.php"; ?>
<?php include "footer.php"; ?>